### PR TITLE
Finite splitter wall

### PR DESCRIPTION
**Pull request by omdowley**
Adds a finite splitter wall.

### CODE REVIEW

**Comment by Datseris** [comment]
Great! Have you done any tests with it? Does it work as expected? We could be adding something to the test suite. 

(I saw you didn't write any actual ray-splitting code. This wasn't necessary? How come?)

**Comment by omdowley** [comment]
I've mostly run a single bit of test code - modelling total internal reflections inside a medium. In that setup it seems to be behaving correctly: I'm sending particles in, and getting refractions and reflections as I would expect without any of the side-effects I was seeing from infinite walls. 

It does make sense that this will need something in the test suite - I'm not sure I have enough knowledge of this codebase to really have a good idea of what the worst cases to test for this sort of thing are. I'll have a look at the existing tests, but input definitely appreciated. I can confirm that this doesn't break anything though; I've run the existing tests which all pass.

I didn't have to write any ray-splitting code because the test for supporting ray-splitting is just whether an Obstacle has a pflag. The `normalvec` also needed to be defined correctly across the struct for it to work, but that was it as far as I could see.

**Comment by Datseris** [comment]
> I didn't have to write any ray-splitting code because the test for supporting ray-splitting is just whether an Obstacle has a pflag. The normalvec also needed to be defined correctly across the struct for it to work, but that was it as far as I could see.

Damn, I have forgotten how good the design of this library was. You're right, that's all it takes. 

The test suite in this package was set up in an advance manner, but we don't have to worry. Here is what I propose: go to the file `test/raysplt_tests.jl`. There open a new code block:
```julia
@testset "FiniteSplitterWall" begin
    # code
end
```
In there make a trivial rectangle billiard that has in the middle a finite splitter wall. Give it a 50% chance of transmission. Initialize 500 particles on the left with direction towards the right (use e.g. `particlebeam`), and evolve them for 2 collisions. About half of them should be in the right side of the billiad and the other half on the left. so you could do something like ` n = number of particles on the left`, and then `@test 0.3 < n < 0.7` .

**Comment by Datseris** [comment]
(Ah, also don't forget to increment minor version in Project.toml file and add a small entry in CHANGELOG.md)

**Comment by Datseris** [comment]
Oh yeah sorry, also forgot that you need to put this in the docs in Obstacle library. In `docs/src/tutorials/billiard_table.md`

**Comment by omdowley** [comment]
Ah, no worries. Let me also check if I can find anywhere in the ray-splitting tutorial I should update.

**Comment by Datseris** [comment]
Thank you very much for the contribution!

**Pull request merged**
