### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by Datseris** [comment]
Hm seems to fail because of Conda. 
```
  Building Conda ─→ `C:\Users\appveyor\.julia\packages\Conda\S0nV\deps\build.log`
  Building PyCall → `C:\Users\appveyor\.julia\packages\PyCall\fiJ3\deps\build.log`
ERROR: MethodError: no method matching haskey(::Nothing, ::String)
Closest candidates are:
  haskey(!Matched::Base.Iterators.Pairs, ::Any) at iterators.jl:246
  haskey(!Matched::Dict, ::Any) at dict.jl:555
  haskey(!Matched::Base.ImmutableDict, ::Any) at dict.jl:740
  ...
Stacktrace:
 [1] _get_deps!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUID,1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\Pkg\src\API.jl:362
 [2] _get_deps!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUID,1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\Pkg\src\API.jl:366 (repeats 2 times)
 [3] #build#51(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\Pkg\src\API.jl:400
 [4] build at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\Pkg\src\API.jl:377 [inlined]
 [5] build at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\Pkg\src\API.jl:374 [inlined]
 [6] build() at C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v0.7\Pkg\src\API.jl:371
 [7] top-level scope at none:0
Command exited with code 1
```
However, let me say that there is no reason to build PyCall on appveyor. I am only using it for building the documentation so only the travis build actually needs it. I am sure everything will be much better once `Requires` is working again!

**Comment by KristofferC** [comment]
Alright!

**Comment by KristofferC** [comment]
Passes on nightly but not on beta (which is to be expected) https://ci.appveyor.com/project/JuliaDynamics/dynamicalbilliards-jl-wt09b/build/1.0.189/job/ms8fv9e4uvi515nv.

**Comment by Datseris** [comment]
Yeap, just saw it, thanks a lot!

**Pull request merged**
